parser:
    university:
      name:
        sstu: "Yuri Gagarin State Technical University of Saratov"
      url:
        sstu: "http://rasp.sstu.ru/"
server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}/schedule_scrapper
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver